services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-mini-crm
    container_name: mini_crm_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
    networks:
      - mini_crm_network

networks:
  mini_crm_network:
    driver: bridge
